test3/Controllers/QLDController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using test3.Models;

namespace test3.Controllers
{
    public class QLDController : Controller
    {
        // GET: QLD
        QLSVEntities db = new QLSVEntities();
        public ActionResult DanhSachBangDiem(int? page, int? pageSize)
        {
            if (page == null)
            {
                page = 1;
            }
            if (pageSize == null)
            {
                pageSize = 10;
            }
            var diem = db.BangDiems.ToList();
            return View(diem.ToPagedList((int)page, (int)pageSize));
        }
        [HttpGet]
        public ActionResult Search(string searchMSSV, string searchMaMon,string searchMaLop)
        {
            List<BangDiem> searchResults = new List<BangDiem>();

            if (!string.IsNullOrEmpty(searchMSSV) && !string.IsNullOrEmpty(searchMaMon))
            {
                searchResults = db.BangDiems
                    .Where(s => s.MSSV == searchMSSV && s.MaMon == searchMaMon)
                    .ToList();
            }
            else if (!string.IsNullOrEmpty(searchMSSV))
            {
                searchResults = db.BangDiems
                    .Where(s => s.MSSV == searchMSSV)
                    .ToList();
            }
            else if (!string.IsNullOrEmpty(searchMaMon))
            {
                searchResults = db.BangDiems
                    .Where(s => s.MaMon == searchMaMon)
                    .ToList();
            }
            else if (!string.IsNullOrEmpty(searchMaLop))
            {
                searchResults = db.BangDiems
                    .Where(s => s.MaLop == searchMaLop)
                    .ToList();
            }
            return View("DanhSachBangDiem", searchResults);
        }

        [HttpGet]
        public ActionResult ThemBangDiem()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemBangDiem(BangDiem bangdiem)
        {
            QLSVEntities db = new QLSVEntities();
            db.BangDiems.Add(bangdiem);
            db.SaveChanges();
            return RedirectToAction("DanhSachBangDiem");
        }
        public ActionResult Xoa(string MSSV)
        {
            QLSVEntities db = new QLSVEntities();
            var BangDiem = db.BangDiems.Find(MSSV);
            db.BangDiems.Remove(BangDiem);
            db.SaveChanges();
            return RedirectToAction("DanhSachBangDiem");
        }
        [HttpGet]
        public ActionResult SuathongtinBangDiem(string bangDiem)
        {
            QLSVEntities db = new QLSVEntities();
            var BangDiem = db.BangDiems.Find(bangDiem);
            return View(BangDiem);
        }
        [HttpPost]
        public ActionResult SuathongtinBangDiem(BangDiem bangdiem)
        {
            db.Entry(bangdiem).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("DanhSachBangDiem");
        }
    }
}

test3/Controllers/QLGVController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using test3.Models;

namespace test3.Controllers
{
    public class QLGVController : Controller
    {
        // GET: QLGV
        QLSVEntities db = new QLSVEntities();
        public ActionResult DanhSachGiangVien(int? page, int? pageSize)
        {
            if (page == null)
            {
                page = 1;
            }
            if (pageSize == null)
            {
                pageSize = 10;
            }
            var giangVien = db.GiangViens.ToList();
            return View(giangVien.ToPagedList((int)page, (int)pageSize));
        }
        [HttpGet]
        public ActionResult Search(string searchMGV)
        {
            List<GiangVien> searchMgv = db.GiangViens.Where(s => s.MGV == searchMGV).ToList();

            return View("DanhSachGiangVien", searchMgv);
        }
        [HttpGet]
        public ActionResult ThemMoiGiangVien()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ThemMoiGiangVien(GiangVien giangVien)
        {
            if (string.IsNullOrEmpty(giangVien.GvUser))
            {
                ViewBag.GvUserError = "Yêu cầu nhập tài khoản giảng viên.";
            }
            if (string.IsNullOrEmpty(giangVien.GvPass))
            {
                ViewBag.GvPassError = "Yêu cầu nhập mật khẩu giảng viên.";
            }
            if (string.IsNullOrEmpty(giangVien.HoTenGV))
            {
                ViewBag.HoTenGVError = "Yêu cầu nhập họ tên giảng viên.";
            }

            if (string.IsNullOrEmpty(giangVien.MGV))
            {
                ViewBag.MGVError = "Yêu cầu nhập mã giảng viên.";
            }
            else
            {
                using (QLSVEntities db = new QLSVEntities())
                {
                    // Kiểm tra xem MGV đã tồn tại trong cơ sở dữ liệu hay chưa
                    if (db.GiangViens.Any(gv => gv.MGV == giangVien.MGV))
                    {
                        ViewBag.MGVError = "Mã giảng viên đã tồn tại. Vui lòng sử dụng mã khác.";
                    }
                }
            }

            if (giangVien.NgaySinhGV == null || giangVien.NgaySinhGV == DateTime.MinValue)
            {
                ViewBag.NgaySinhGVError = "Yêu cầu nhập ngày sinh giảng viên.";
            }
            else
            {
                int currentYear = DateTime.Now.Year;
                int birthYear = giangVien.NgaySinhGV.Year;
                int age = currentYear - birthYear;

                if (age < 18)
                {
                    ViewBag.NgaySinhGVError = "Chưa đủ 18 tuổi.";
                }
                else
                {
                    try
                    {
                        using (QLSVEntities db = new QLSVEntities())
                        {
                            db.GiangViens.Add(giangVien);
                            db.SaveChanges();
                            return RedirectToAction("DanhSachGiangVien");
                        }
                    }
                    catch (Exception ex)
                    {
                        ViewBag.ErrorMessage = "Có lỗi xảy ra khi thêm giảng viên: " + ex.Message;
                    }
                }
            }

            // Kiểm tra trường "GioiTinh"
            if (giangVien.GioiTinh == null)
            {
                ViewBag.GioiTinhError = "Yêu cầu chọn giới tính giảng viên.";
            }

            if (string.IsNullOrEmpty(giangVien.MaKhoa))
            {
                ViewBag.MaKhoaError = "Yêu cầu chọn mã khoa giảng viên.";
            }

            return View(giangVien);
        }





        public ActionResult Xoa(string id)
        {
            QLSVEntities db = new QLSVEntities();
            var giangVien = db.GiangViens.Find(id);
            db.GiangViens.Remove(giangVien);
            db.SaveChanges();
            return RedirectToAction("DanhSachGiangVien");
        }
        [HttpGet]
        public ActionResult Suathongtin(string id)
        {
            QLSVEntities db = new QLSVEntities();
            var giangVien = db.GiangViens.Find(id);

            ViewBag.KhoaCu = giangVien.MaKhoa;
            return View(giangVien);
        }
        [HttpPost]
        public ActionResult Suathongtin(GiangVien giangVien)
        {
            if (string.IsNullOrEmpty(giangVien.GvUser))
            {
                ViewBag.GvUserError = "Yêu cầu nhập tài khoản giảng viên.";
            }
            if (string.IsNullOrEmpty(giangVien.GvPass))
            {
                ViewBag.GvPassError = "Yêu cầu nhập mật khẩu giảng viên.";
            }
            if (string.IsNullOrEmpty(giangVien.HoTenGV))
            {
                ViewBag.HoTenGVError = "Yêu cầu nhập họ tên giảng viên.";
            }

            if (giangVien.NgaySinhGV == null || giangVien.NgaySinhGV == DateTime.MinValue)
            {
                ViewBag.NgaySinhGVError = "Yêu cầu nhập ngày sinh giảng viên.";
            }
            else
            {
                int currentYear = DateTime.Now.Year;
                int birthYear = giangVien.NgaySinhGV.Year;
                int age = currentYear - birthYear;

                if (age < 18)
                {
                    ViewBag.NgaySinhGVError = "Chưa đủ 18 tuổi.";
                }
                else
                {
                    try
                    {
                        using (QLSVEntities db = new QLSVEntities())
                        {
                            db.Entry(giangVien).State = EntityState.Modified;
                            db.SaveChanges();
                            return RedirectToAction("DanhSachGiangVien");
                        }
                    }
                    catch (Exception ex)
                    {
                        ViewBag.ErrorMessage = "Có lỗi xảy ra khi thêm giảng viên: " + ex.Message;
                    }
                }
            }

            // Kiểm tra trường "GioiTinh"
            if (giangVien.GioiTinh == null)
            {
                ViewBag.GioiTinhError = "Yêu cầu chọn giới tính giảng viên.";
            }

            if (string.IsNullOrEmpty(giangVien.MaKhoa))
            {
                ViewBag.MaKhoaError = "Yêu cầu chọn mã khoa giảng viên.";
            }

            return View(giangVien);
        }



        [HttpGet]
        public ActionResult ThemMoiTinTuc()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ThemMoiTinTuc(TinTuc tintuc)
        {
            if (string.IsNullOrEmpty(tintuc.TieuDe))
            {
                ViewBag.TieuDeError = "Yêu cầu nhập tiêu đề.";
                return View(tintuc);
            }
            if (string.IsNullOrEmpty(tintuc.NoiDung))
            {
                ViewBag.HoTenGVError = "Yêu cầu nhập nội dung.";
                return View(tintuc);
            }
            QLSVEntities db = new QLSVEntities();
            db.TinTucs.Add(tintuc);
            db.SaveChanges();
            return RedirectToAction("DashBoard","Home");
        }

    }
}

test3/Controllers/QLKController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using test3.Models;

namespace test3.Controllers
{
    public class QLKController : Controller
    {
        // GET: QLK
        QLSVEntities db = new QLSVEntities();
        public ActionResult DanhSachKhoa(int? page, int? pageSize)
        {
            if (page == null)
            {
                page = 1;
            }
            if (pageSize == null)
            {
                pageSize = 10;
            }
            var khoa = db.Khoas.ToList();
            return View(khoa.ToPagedList((int)page, (int)pageSize));
        }
        [HttpGet]
        public ActionResult ThemMoiKhoa()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ThemMoiKhoa(Khoa khoa)
        {
            QLSVEntities db = new QLSVEntities();
            db.Khoas.Add(khoa);
            db.SaveChanges();
            return RedirectToAction("DanhSachKhoa");
        }
        public ActionResult Xoa(string maKhoa)
        {
            QLSVEntities db = new QLSVEntities();
            var khoa = db.Khoas.Find(maKhoa);
            db.Khoas.Remove(khoa);
            db.SaveChanges();
            return RedirectToAction("DanhSachKhoa");
        }
        [HttpGet]
        public ActionResult Suathongtin(string maKhoa)
        {
            QLSVEntities db = new QLSVEntities();
            var khoa = db.Khoas.Find(maKhoa);
            return View(khoa);
        }
        [HttpPost]
        public ActionResult Suathongtin(Khoa khoa)
        {
            db.Entry(khoa).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("DanhSachKhoa");
        }
    }
}

test3/Controllers/QLLController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using test3.Models;

namespace test3.Controllers
{
    public class QLLController : Controller
    {
        // GET: QLL
        QLSVEntities db = new QLSVEntities();
        public ActionResult DanhSachLop(int? page, int? pageSize)
        {
            if (page == null)
            {
                page = 1;
            }
            if (pageSize == null)
            {
                pageSize = 10;
            }
            var lop = db.Lops.ToList();
            return View(lop.ToPagedList((int)page, (int)pageSize));
        }
        [HttpGet]
        public ActionResult ThemMoiLop()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Search(string search)
        {
            // Tìm kiếm sinh viên dựa trên MaLop và MaKhoa
            List<Lop> searchResults = db.Lops
              .Where(s => s.MaLop.StartsWith(search) || s.MaKhoa.StartsWith(search))
              .ToList();


            // Trả về view hiển thị danh sách sinh viên kết quả
            return View("DanhSachLop", searchResults);
        }

        [HttpPost]
        public ActionResult ThemMoiLop(Lop lop)
        {
            QLSVEntities db = new QLSVEntities();
            db.Lops.Add(lop);
            db.SaveChanges();
            return RedirectToAction("DanhSachLop");
        }
        public ActionResult Xoa(string maLop)
        {
            QLSVEntities db = new QLSVEntities();
            var lop = db.Lops.Find(maLop);
            db.Lops.Remove(lop);
            db.SaveChanges();
            return RedirectToAction("DanhSachLop");
        }
        [HttpGet]
        public ActionResult Suathongtin(string maLop)
        {
            QLSVEntities db = new QLSVEntities();
            var lop = db.Lops.Find(maLop);
            return View(lop);
        }
        [HttpPost]
        public ActionResult Suathongtin(Lop lop)
        {
            db.Entry(lop).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("DanhSachLop");
        }
    }
}

test3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Quản lí sinh viên</title>
    <!-- BOOTSTRAP STYLES-->
    <link href="~/Content/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="~/Content/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- MORRIS CHART STYLES-->
    <link href="~/Content/assets/js/morris/morris-0.4.3.min.css" rel="stylesheet" />
    <!-- CUSTOM STYLES-->
    <link href="~/Content/assets/css/custom.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

    <!-- JQUERY SCRIPTS -->
    <script src="~/Content/assets/js/jquery-1.10.2.js"></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="~/Content/assets/js/bootstrap.min.js"></script>
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-brand" href="index.html"><img src="https://media.huce.edu.vn/Media/2_SINHVIEN/FolderFunc/202304/Images/logodhxd-20230421024916-e.png" style="max-height: 40px;"></a>
            </div>
            <div style="color: white;padding: 15px 50px 5px 50px;float: right;font-size: 16px;"> <a href="#" class="btn btn-danger square-btn-adjust">Tin tức</a> &nbsp; <a href="@Url.Action("Login", "Dangnhap")" class="btn btn-danger square-btn-adjust">Logout</a> </div>
        </nav>

        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li>
                        <a class="@Html.Raw(ViewBag.ac == 1 ? "active-menu" : "")" href="@Url.Action("DashBoard", "Home" )"><i class="fa fa-dashboard fa-3x"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="#" class="@Html.Raw(ViewBag.ac == 2 || ViewBag.ac == 3? "active-menu" : "")"><i class="fa fa-sitemap fa-3x"></i> Sinh Viên<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="@Html.Raw(ViewBag.ac == 2 ? "active-menu" : "")" href="@Url.Action("DanhSachSinhVien", "QLSV" )">Danh sách sinh viên</a>
                            </li>
                            <li>
                                <a class="@Html.Raw(ViewBag.ac == 3 ? "active-menu" : "")" href="@Url.Action("ThemMoiSinhVien", "QLSV")">Thêm mới sinh viên</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="@Html.Raw(ViewBag.ac == 4 || ViewBag.ac == 5|| ViewBag.ac == 6? "active-menu" : "")"><i class="fa fa-desktop fa-3x"></i> Giảng viên<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li class="nav nav-second-level">
                                <a class="@Html.Raw(ViewBag.ac == 4 ? "active-menu" : "")" href="@Url.Action("DanhSachGiangVien", "QLGV")">Danh sách giảng viên</a>
                            </li>
                            <li>
                                <a class="@Html.Raw(ViewBag.ac == 5 ? "active-menu" : "")" href="@Url.Action("ThemMoiGiangVien", "QLGV")">Thêm mới giảng viên</a>
                            </li>
                            <li>
                                <a class="@Html.Raw(ViewBag.ac == 6 ? "active-menu" : "")" href="@Url.Action("ThemMoiTinTuc", "QLGV")">Thêm mới tin tức</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="@Html.Raw(ViewBag.ac == 7 || ViewBag.ac == 8? "active-menu" : "")"><i class="fa fa-sitemap fa-3x"></i> Khoa<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="@Html.Raw(ViewBag.ac == 7 ? "active-menu" : "")" href="@Url.Action("DanhSachKhoa", "QLK" )">Danh sách khoa</a>
                            </li>
                            <li>
                                <a class="@Html.Raw(ViewBag.ac == 8 ? "active-menu" : "")" href="@Url.Action("ThemMoiKhoa", "QLK")">Thêm mới khoa</a>
                            </li>
                        </ul>

                    </li>
                    <li>
                        <a href="#" class="@Html.Raw(ViewBag.ac == 9 || ViewBag.ac == 10? "active-menu" : "")"><i class="fa fa-desktop fa-3x"></i>Môn Học<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li class="nav nav-second-level">
                                <a class="@Html.Raw(ViewBag.ac == 9 ? "active-menu" : "")" href="@Url.Action("DanhSachMonHoc", "QLMH")">Danh sách môn học</a>
                            </li>
                            <li>
                                <a class="@Html.Raw(ViewBag.ac == 10 ? "active-menu" : "")" href="@Url.Action("ThemMonHoc", "QLMH")">Thêm mới môn học</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="@Html.Raw(ViewBag.ac == 11 || ViewBag.ac == 12? "active-menu" : "")"><i class="fa fa-sitemap fa-3x"></i> Lớp<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="@Html.Raw(ViewBag.ac == 11 ? "active-menu" : "")" href="@Url.Action("DanhSachLop", "QLL" )">Danh sách lớp</a>
                            </li>
                            <li>
                                <a class="@Html.Raw(ViewBag.ac == 12 ? "active-menu" : "")" href="@Url.Action("ThemMoiLop", "QLL")">Thêm mới lớp</a>
                            </li>
                        </ul>

                    </li>

                    <li>
                        <a href="#" class="@Html.Raw(ViewBag.ac == 13 || ViewBag.ac == 14? "active-menu" : "")"><i class="fa fa-sitemap fa-3x"></i> Điểm<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="@Html.Raw(ViewBag.ac == 13 ? "active-menu" : "")" href="@Url.Action("DanhSachBangDiem", "QLD" )">Danh sách điểm</a>
                            </li>
                            <li>
                                <a class="@Html.Raw(ViewBag.ac == 14 ? "active-menu" : "")" href="@Url.Action("ThemBangDiem", "QLD")">Nhập điểm</a>
                            </li>
                        </ul>
                </ul>

            </div>

        </nav>

        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            @RenderBody()


            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- METISMENU SCRIPTS -->
    <script src="~/Content/assets/js/jquery.metisMenu.js"></script>
    <!-- MORRIS CHART SCRIPTS -->
    <script src="~/Content/assets/js/morris/raphael-2.1.0.min.js"></script>
    <script src="~/Content/assets/js/morris/morris.js"></script>
    <!-- CUSTOM SCRIPTS -->
    <script src="~/Content/assets/js/custom.js"></script>


</body>
</html>